### ISSUE TITLE
NullPointerException: Exception ticking world Crash

### ISSUE THREAD

**Issue by ikuy** [Chicken-Bones/CodeChickenLib#33]
Apologize me if I'm making any mistake on starting a new issue, if so let me correct it.

I'v been encountering this crash many times recently but failed to track what exactly causes this so I've got no choose but asking you, because there is
"at codechicken.lib.world.WorldExtension.unloadChunk"
in the crash report :P

The full crash report goes:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/5/15 4:16 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at codechicken.lib.world.WorldExtension.unloadChunk(WorldExtension.java:52)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_317_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:1053)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:482)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.lib.world.WorldExtension.unloadChunk(WorldExtension.java:52)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_317_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:1053)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:482)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['kas'/133940, l='world', x=-217.56, y=74.00, z=501.94](kas at -217.5629707694222,74.0,501.9429785611462), EntityPlayerMP['fxr'/235096, l='world', x=-236.00, y=67.00, z=489.33](fxr at -236.00253176495278,67.0,489.33204579224105)]
	Chunk stats: ServerChunkCache: 707 Drop: 196
	Level seed: 101614
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-147,67,195), Chunk: (at 13,4,3 in -10,12; contains blocks -160,0,192 to -145,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4126321 game time, 4111383 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 82513 (now: false), thunder time: 81167 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 188708784 bytes (179 MB) / 1230503936 bytes (1173 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 4 total; -Xmx10240M -Xms1024M -XX:PermSize=1024M -XX:MaxPermSize=2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 37, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1231 Cauldron-MCPC-Plus vgit-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1231 52 mods loaded, 52 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1231} [Forge Mod Loader] (cauldron-1.7.10-1.1231.04.209-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1231} [Minecraft Forge] (cauldron-1.7.10-1.1231.04.209-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-beta-7} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppleCore{1.0.2} [AppleCore] (AppleCore-mc1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-beta-7} [Applied Energistics 2] (appliedenergistics2-rv2-beta-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.658-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.658-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraveStone{2.11.1} [GraveStone] (GraveStone 2.11.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	InfernalMobs{1.5.4} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_Invasion{1.1.5} [Invasion] (Invasion_1.1.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct] (TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.5.8.59} [ProjectRed] (ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.5.8.59} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transportation{4.5.8.59} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Exploration{4.5.8.59} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.8.59-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Compatibility{4.5.8.59} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.8.59-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.5.8.59} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Illumination{4.5.8.59} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.8.59-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Expansion{4.5.8.59} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HungerOverhaul{1.7.10-beta.4.jenkins44} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: beta rv2-beta-7 for Forge 10.13.2.1230
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 3 / 50; [EntityPlayerMP['kas'/133940, l='world', x=-217.56, y=74.00, z=501.94](kas at -217.5629707694222,74.0,501.9429785611462), EntityPlayerMP['UCMP5'/211586, l='DIM-1', x=-19.57, y=80.00, z=-33.34](UCMP5 at -19.57300545607935,80.0,-33.34258504148861), EntityPlayerMP['fxr'/235096, l='world', x=-236.00, y=67.00, z=489.33](fxr at -236.00253176495278,67.0,489.33204579224105)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

If this is caused by other mod please let me know, thanks.

And there's another exception, or called [Thread-128/WARN]&[Thread-128/ERROR]. This one won't crash the server but it just spawn a lot in the console. In it appears many mod name but I'm not sure which one actually spawn this errors. Could you please help me?

[18:51:22] [Thread-128/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.ChunkDataEvent$Save@50426bf8:
java.lang.NullPointerException
	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:62) ~[WorldExtension.class:?]
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:42) ~[WorldExtensionManager$WorldExtensionEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_316_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:219) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:418) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1052) [mt.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:791) [CraftWorld.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at com.mengcraft.bukkit.protect.SaveWorld$SaveWorldTask.run(SaveWorld.java:65) [ProtectPlugin.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
[18:51:22] [Thread-128/ERROR] [FML/]: Index: 4 Listeners:
[18:51:22] [Thread-128/ERROR] [FML/]: 0: NORMAL
[18:51:22] [Thread-128/ERROR] [FML/]: 1: ASM: thaumcraft.common.lib.events.EventHandlerWorld@8facabd chunkSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/ERROR] [FML/]: 2: ASM: mods.natura.Natura@52ea5ec chunkDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/ERROR] [FML/]: 3: ASM: mods.natura.worldgen.retro.WorldHandler@1616b500 handleChunkSaveEvent(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/ERROR] [FML/]: 4: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@733b791e onChunkDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/WARN] [/]: java.lang.NullPointerException
[18:51:22] [Thread-128/WARN] [/]: 	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:62)
[18:51:22] [Thread-128/WARN] [/]: 	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:42)
[18:51:22] [Thread-128/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_316_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic)
[18:51:22] [Thread-128/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[18:51:22] [Thread-128/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:219)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:418)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1052)
[18:51:22] [Thread-128/WARN] [/]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:791)
[18:51:22] [Thread-128/WARN] [/]: 	at com.mengcraft.bukkit.protect.SaveWorld$SaveWorldTask.run(SaveWorld.java:65)
[18:51:22] [Thread-128/WARN] [/]: 	at java.lang.Thread.run(Unknown Source)
[18:51:22] [Thread-128/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.ChunkDataEvent$Save@1d2c1f31:
java.lang.NullPointerException
	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:62) ~[WorldExtension.class:?]
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:42) ~[WorldExtensionManager$WorldExtensionEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_316_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:219) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:418) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1052) [mt.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:791) [CraftWorld.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at com.mengcraft.bukkit.protect.SaveWorld$SaveWorldTask.run(SaveWorld.java:65) [ProtectPlugin.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
[18:51:22] [Thread-128/ERROR] [FML/]: Index: 4 Listeners:
[18:51:22] [Thread-128/ERROR] [FML/]: 0: NORMAL
[18:51:22] [Thread-128/ERROR] [FML/]: 1: ASM: thaumcraft.common.lib.events.EventHandlerWorld@8facabd chunkSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/ERROR] [FML/]: 2: ASM: mods.natura.Natura@52ea5ec chunkDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/ERROR] [FML/]: 3: ASM: mods.natura.worldgen.retro.WorldHandler@1616b500 handleChunkSaveEvent(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/ERROR] [FML/]: 4: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@733b791e onChunkDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:51:22] [Thread-128/WARN] [/]: java.lang.NullPointerException
[18:51:22] [Thread-128/WARN] [/]: 	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:62)
[18:51:22] [Thread-128/WARN] [/]: 	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:42)
[18:51:22] [Thread-128/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_316_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic)
[18:51:22] [Thread-128/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[18:51:22] [Thread-128/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:219)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:418)
[18:51:22] [Thread-128/WARN] [/]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1052)
[18:51:22] [Thread-128/WARN] [/]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:791)
[18:51:22] [Thread-128/WARN] [/]: 	at com.mengcraft.bukkit.protect.SaveWorld$SaveWorldTask.run(SaveWorld.java:65)
[18:51:22] [Thread-128/WARN] [/]: 	at java.lang.Thread.run(Unknown Source)

here's only two of them, each of them has a different string following 
"ChunkDataEvent$Save", for example "ChunkDataEvent$Save" + "@50426bf8"

I'm using CodeChickenLib-1.7.10-1.1.1.110-universal.jar

**Comment by smenes** [comment]
same for me
http://pastebin.com/raw.php?i=yXLxBDhg

**Comment by Cuppycake** [comment]
Ditto 
http://pastebin.com/S9Q1w1zQ

**Comment by neosatan** [comment]
I have quite the same exception.  Thus for me it occurs only when I go into a mystcraft age. Whole mystcraft experience is quite hard on me, since, I can not do anything reasonable. The age generates correctly, then after couple of minutes all blocks disappear (like with corrupted chunks in overworld). When I try reload the world I get following exception:

http://pastebin.com/FwP6SmKs

**Comment by Swordsyke** [comment]
Same error going on here.
http://pastebin.com/HxXUC3Bt
I have already removed Mystcraft from the server, so that isn't the issue.

**Comment by Swordsyke** [comment]
I discovered that the error was fixed by reverting to an older version of kCauldron. Somehow, I think the new version of codechicken.lib incorrectly references or interacts with the newer versions and causes issues.

**Comment by StargateMC** [comment]
@Swordsyke What version did you go back to?

**Comment by StargateMC** [comment]
@robotia any ideas bud? :)
